x-build: &x-build
  build:
    context: .
    args:
      USERNAME: $USER

x-common: &x-common
  image: mochi-container
  volumes:
    - .:/home/$USER/workspace:cached
  init: true
  networks:
    - mochi_net
  cap_add:
    - SYS_ADMIN
    - SYS_PTRACE
  devices:
    - /dev/fuse
  security_opt:
    - seccomp:unconfined
    - apparmor:unconfined
  privileged: false
  command: >
    bash -c "sudo service ssh restart && sleep infinity"

services:
  c1:
    <<: [*x-build, *x-common]
    hostname: c1
    container_name: mochi-c1
  c2:
    <<: *x-common
    hostname: c2
    container_name: mochi-c2
  c3:
    <<: *x-common
    hostname: c3
    container_name: mochi-c3
  c4:
    <<: *x-common
    hostname: c4
    container_name: mochi-c4

networks:
  mochi_net:
